### ISSUE TITLE
Update references to travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by geneorama** [Chicago/dev.cityofchicago.org#100]
The only place I see it now is in the readme

@levyj would you mind doing this with the other updates to the blog?

**Comment by levyj** [comment]
@geneorama - What needs to be done? Is this in each individual post? I was not aware of that.

**Comment by geneorama** [comment]
I was just suggesting to update the address in the readme, I don't think it appears anywhere else. I can update it as well tomorrow if you don't see it.

**Comment by levyj** [comment]
I think this pull request would do that. See what you think. Thanks.

**Comment by geneorama** [comment]
Thanks Jon! Yes looked perfect, I didn't see the change the first time.

**Comment by levyj** [comment]
@geneorama - So, this was completed by https://github.com/Chicago/dev.cityofchicago.org/pull/101 and can be closed, right?

**Comment by geneorama** [comment]
@levyj yes
