### ISSUE TITLE
Experiment with "motion" gifs for header images

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/dev.cityofchicago.org#15]
Static images in the hero background look nice, but interested in experimenting with subtle gifs that have some noticable movement, but nothing too dramatic.

**Comment by tomschenkjr** [comment]
@geneorama - I pushed an example of this, though, we cannot use it because it's an All-Rights-Reserved copyrighted image. You can look at it by cloning the repo and looking at the `issue15` branch. You'll need to have Jekyll (and Ruby) installed. Then you can navigate to the page and run:

``` bash
bundle exec jekyll serve
```

After it's done building, then navigate to `localhost:4000` in your web browser.

**Comment by geneorama** [comment]
That's really slick, I love the effects. I especially like how the there is motion in the atmosphere and cars, but the buildings are clearly static. 

I don't know that the dark colors are appropriate / inviting for the purpose of the site. It feels like I found a website for a new club, or a top secret late night coding meetup.

**Comment by tomschenkjr** [comment]
If you ever find a good, sufficiently large creative commons or otherwise “open source” image with some motion, I’d love to include it. Often, these images are culled from videos—which are rarely ever open. Sometimes it takes some investigation because people will post these GIFs on Tumblr or Giphy w/o attribution.

This image in particular is from https://vimeo.com/76293321

**Comment by geneorama** [comment]
I've seen that video on Facebook a couple of times, it's amazing. Looks like each of his camera rigs probably cost around $10k, and he had multiple cameras and spent weeks making the shots.  So it's not like we'll find the same thing "only lighter" and also open source.
