### ISSUE TITLE
Broken link in open311 rotating image

### ISSUE THREAD

**Issue by geneorama** [Chicago/dev.cityofchicago.org#59]
The link in this image points to http://dev.cityofchicago.org/docs/api

I believe it should point to http://dev.cityofchicago.org/docs/open311/

![image](https://user-images.githubusercontent.com/1392068/50024611-94c00180-ffa8-11e8-98cb-6e95dfc5812e.png)

**Comment by diffractometer** [comment]
Opened up a PR here: https://github.com/Chicago/dev.cityofchicago.org/pull/60

Let me know if it helps.
