### ISSUE TITLE
Links to resources do not work when not starting from home page

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/dev.cityofchicago.org#88]
## Description

Accessing any of the links under the Resources page returns a 404 if you don't start from the homepage (dev.cityofchicago.org). It appears the relative paths are incorrect so leads to odd links.

### A working scenario

1. Visit dev.cityofchicago.org
2. Hover mouse over "Resources"
3. Select "Lead Safe"
4. Returns the correct site (http://dev.cityofchicago.org/docs/lead-safe/)

### Returns a broken link

1. Visit the blog page (http://dev.cityofchicago.org/blog/)
2. Hover mouse over "Resources"
3. Select Lead Safe
4. Step 3 points you to [this page](http://dev.cityofchicago.org/blog/docs/docs/lead-safe) which returns a 404 error

**Comment by geneorama** [comment]
Although it's an imperfect fix, the only thing I can find that works is using absolute links.

**Comment by geneorama** [comment]
This issue is possibly related to https://github.com/Chicago/open311-api-docs/issues/14

From the name the error thrown when creating the documentation (`ERROR   -  Config value: 'markdown_extensions'. Error: Failed loading extension "toc(permalink=true)".`) could be related.
